site_name: /reg/nal docs
site_url: https://regn.al/docs
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    search.suggest
    search.highlight
    content.action.edit
  palette:
    scheme: slate
    primary: brown
    accent: teal


repo_url: https://github.com/tyrantlink/regnal
repo_name: tyrantlink/regnal
edit_uri: edit/master/docs/
plugins:
  - search
markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
copyright: documentation is hard >.<