[package]
name = "regnalrb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "regnalrb"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
qrcode-generator = "4.1.9"